# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c543df66f98581efe5a0ea6451fb45119d529c3c4dd32f1d731f1b51c15f09c96fa48a4745666e8cfd1e925c4422fdc79ab48e6243f8f3b600859c865dcee07d

test:
  secret_key_base: b606978333000fc44df032619ddea162e921e27d39bad62088bb8cd5387fac66c34ba1d41c64d1c97bfabf14f67e3f5f4212f22797832848b93804c9877fa06c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
